"""Serialize built FSMs to plain data (for the codex's machine.yaml dumps).

The builders are the source of truth; these dumps make the GENERATED
machines visible — greppable states, transitions, conditions, and
emissions — tagged with the factory that produced them. They are
write-only artifacts (regenerated by codex/build_catalog.py, freshness
test-enforced), not an input format.
"""

from __future__ import annotations

from typing import Any

from fsm_parser.fsm import (
    FSM,
    Always,
    And,
    AtSentenceEnd,
    AtSentenceStart,
    CaptureAnchor,
    FiringOffset,
    HasAllLabels,
    HasAnyLabel,
    HasLabel,
    Never,
    Not,
    Or,
    ScanEnd,
    ScanStart,
    WeightAbove,
    WeightBelow,
)


def condition_to_data(cond) -> Any:
    if isinstance(cond, HasLabel):
        return {"has": cond.label} if cond.min_weight == 0.0 else \
            {"has": cond.label, "min_weight": cond.min_weight}
    if isinstance(cond, HasAnyLabel):
        return {"has_any": list(cond.labels)}
    if isinstance(cond, HasAllLabels):
        return {"has_all": list(cond.labels)}
    if isinstance(cond, Not):
        return {"not": condition_to_data(cond.inner)}
    if isinstance(cond, And):
        return {"and": [condition_to_data(p) for p in cond.parts]}
    if isinstance(cond, Or):
        return {"or": [condition_to_data(p) for p in cond.parts]}
    if isinstance(cond, Always):
        return {"any": True}
    if isinstance(cond, Never):
        return {"never": True}
    if isinstance(cond, WeightAbove):
        return {"weight_above": cond.label, "threshold": cond.threshold}
    if isinstance(cond, WeightBelow):
        return {"weight_below": cond.label, "threshold": cond.threshold}
    if isinstance(cond, AtSentenceStart):
        return {"at_start": True}
    if isinstance(cond, AtSentenceEnd):
        return {"at_end": True}
    return {"opaque": repr(cond)}  # e.g. LabelPredicate: not data-expressible


def _anchor_to_data(anchor) -> Any:
    if isinstance(anchor, FiringOffset):
        return None if anchor.offset == 0 else {"offset": anchor.offset}
    if isinstance(anchor, CaptureAnchor):
        d = {"capture": anchor.name}
        if anchor.offset:
            d["offset"] = anchor.offset
        return d
    if isinstance(anchor, ScanStart):
        return {"scan_start": anchor.offset}
    if isinstance(anchor, ScanEnd):
        return {"scan_end": anchor.offset}
    return {"opaque": repr(anchor)}


def _emission_to_data(em) -> dict:
    d: dict[str, Any] = {"emit": em.label}
    if em.weight != 1.0:
        d["weight"] = em.weight
    anchor = _anchor_to_data(em.anchor)
    if anchor is not None:
        d["anchor"] = anchor
    return d


def _state_name(s) -> str:
    return s.name if s.name else f"q{s.value}"


def fsm_to_data(fsm: FSM, *, generated_by: str | None = None,
                params: dict | None = None) -> dict:
    """A complete, stable, human-readable dump of a built machine."""
    states = sorted(fsm.states(), key=lambda s: s.value)
    transitions = []
    for src in states:
        for tr in fsm.transitions_from(src):
            t: dict[str, Any] = {
                "from": _state_name(src),
                "to": _state_name(tr.target),
            }
            if tr.epsilon:
                t["epsilon"] = True
            else:
                t["on"] = condition_to_data(tr.condition)
            if tr.weight != 1.0:
                t["weight"] = tr.weight
            if tr.captures:
                t["captures"] = [
                    {"name": c.name, "kind": c.kind,
                     **({"mode": c.mode} if c.mode != "overwrite" else {})}
                    for c in tr.captures
                ]
            if tr.emissions:
                t["emissions"] = [_emission_to_data(e) for e in tr.emissions]
            transitions.append(t)
    data: dict[str, Any] = {
        "machine": fsm.name,
        "generated": True,
        "generated_by": generated_by,
        "params": params or {},
        "states": [_state_name(s) for s in states],
        "start": _state_name(fsm.start),
        "accept": sorted(_state_name(s) for s in fsm.accept),
        "transitions": transitions,
    }
    if fsm.state_info:
        info = {}
        for s, si in fsm.state_info.items():
            entry = {}
            if si.on_enter:
                entry["on_enter"] = [_emission_to_data(e) for e in si.on_enter]
            if si.on_accept:
                entry["on_accept"] = [_emission_to_data(e) for e in si.on_accept]
            info[_state_name(s)] = entry
        data["state_info"] = info
    return data
