"""Regenerate the codex catalogs (CATALOG.md + catalog.jsonl).

Run from anywhere: python codex/build_catalog.py
The jsonl alphabets are measured (signature()), never declared.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from fsm_parser import codex  # noqa: E402


def main() -> None:
    jsonl = codex.catalog_jsonl()
    (codex.CODEX_ROOT / "catalog.jsonl").write_text(jsonl)

    entries = [json.loads(line) for line in jsonl.strip().split("\n")]
    by_kind: dict[str, list[dict]] = {}
    for e in entries:
        by_kind.setdefault(e["kind"], []).append(e)

    lines = ["# Codex catalog", "",
             "GENERATED by build_catalog.py — do not edit. "
             "I/O alphabets are measured from built machines.", ""]
    for kind in sorted(by_kind):
        lines.append(f"## {kind}")
        lines.append("")
        for e in sorted(by_kind[kind], key=lambda x: x["id"]):
            lines.append(f"### `{e['id']}`  ({e['status']})")
            lines.append("")
            lines.append(e.get("notes", ""))
            lines.append("")
            lines.append(f"- path: `codex/{e['path']}`")
            if "factory" in e:
                lines.append(f"- factory: `{e['factory']}`")
            if e.get("schema_params"):
                lines.append(f"- schema params: {', '.join(e['schema_params'])}")
            if "inputs" in e:
                lines.append(f"- inputs ({len(e['inputs'])}): "
                             f"`{' '.join(e['inputs'])}`")
                outs = e["outputs"]
                shown = " ".join(outs[:10]) + (" ..." if len(outs) > 10 else "")
                lines.append(f"- outputs ({len(outs)}): `{shown}`")
            if e.get("imports"):
                lines.append(f"- imports: {', '.join(e['imports'])}")
            if e.get("used_by"):
                lines.append(f"- used by: {', '.join(e['used_by'])}")
            lines.append(f"- search: {', '.join(map(str, e.get('search_terms', [])))}")
            lines.append("")
    (codex.CODEX_ROOT / "CATALOG.md").write_text("\n".join(lines))
    print(f"catalogued {len(entries)} components "
          f"({', '.join(f'{len(v)} {k}' for k, v in sorted(by_kind.items()))})")


if __name__ == "__main__":
    main()
